name: Release

on:
  push:
    tags:
      - "*"

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - uses: nemerosa/ontrack-github-actions-cli-setup@v1
      id: ontrack
      with:
        only-for: nemerosa
        url: https://ontrack.nemerosa.net
        token: ${{ secrets.ONTRACK_TOKEN }}
        github-token: ${{ github.token }}

    - name: Get version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Displays version
      run: echo VERSION=${VERSION}

    - name: Build packages
      run: ./go-executable-build.bash ${VERSION}

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body: Preview version of the CLI
        files: ontrack-cli-*

    - name: Release marker in Ontrack
      run: |
        ontrack-cli build search --project ${{ steps.ontrack.output.project }} --display-branch --commit ${{ github.sha }} --count 1
